nix-cache is a standalone Nix binary cache HTTP server.

** Rationale

   Practical differences with [[https://github.com/edolstra/nix-serve][nix-serve]]:

   - Reliably works with Nix 2.0
   - Significantly more configurable

** Considerations

   - Has to run as root to sign packages, see: [[https://github.com/NixOS/nix/issues/1708][NixOS/nix#1708]]

     This can be eventually resolved either by patching Nix to allow trusted
     users to sign paths, or by extracting privilege-separated signing node.

   - Relies on Nix utilities being present on PATH. Creating Nix NIFs (bindings)
     is a possibility but not pursued at the moment. This means that two
     processes are created on each ~.nar~ request, one to sign the path (or
     ensure that it's signed), and another to dump it.

** Environment variables

   - ~NIX_CACHE_KEY_FILE~: path to privaty key, required; generate one via:
     : nix-store --generate-binary-cache-key foo foo.pub foo.key
   - ~NIX_CACHE_PORT~: HTTP port to listen to; defaults to 17672
   - ~NIX_CACHE_WANT_MASS_QUERY~: see [[https://nixos.org/releases/nix/nix-1.5/manual.pdf][Nix 1.5 PDF manual]], page 85; defaults to 0
   - ~NIX_CACHE_PRIORITY~: lookup order; defaults to 30 (cache.nixos.org uses 40)
   - ~NIX_CACHE_ROOT~: defaults to /nix
